export const iconsLib = [
	{
		prefix: "ai",
		name: "Ant Design Icons",
		description: "Icons from Ant Design",
		totalIcons: 831,
		license: "MIT",
		url: "https://github.com/ant-design/ant-design-icons",
	},
	{
		prefix: "bs",
		name: "Bootstrap Icons",
		description: "Icons from Bootstrap",
		totalIcons: 2716,
		license: "MIT",
		url: "https://github.com/twbs/icons",
	},
	{
		prefix: "bi",
		name: "BoxIcons",
		description: "High quality web icons",
		totalIcons: 1634,
		license: "MIT",
		url: "https://github.com/atisawd/boxicons",
	},
	{
		prefix: "ci",
		name: "Circum Icons",
		description: "Circle-based icons",
		totalIcons: 288,
		license: "MPL-2.0",
		url: "https://circumicons.com/",
	},
	{
		prefix: "cg",
		name: "css.gg",
		description: "Pure CSS icons",
		totalIcons: 704,
		license: "MIT",
		url: "https://github.com/astrit/css.gg",
	},
	{
		prefix: "di",
		name: "Devicons",
		description: "Developer tool icons",
		totalIcons: 192,
		license: "MIT",
		url: "https://vorillaz.github.io/devicons/",
	},
	{
		prefix: "fa",
		name: "Font Awesome 5",
		description: "Popular icon toolkit",
		totalIcons: 1612,
		license: "CC BY 4.0",
		url: "https://fontawesome.com/",
	},
	{
		prefix: "fa6",
		name: "Font Awesome 6",
		description: "Latest Font Awesome icons",
		totalIcons: 2045,
		license: "CC BY 4.0",
		url: "https://fontawesome.com/",
	},
	{
		prefix: "fc",
		name: "Flat Color Icons",
		description: "Colored flat icons",
		totalIcons: 329,
		license: "MIT",
		url: "https://github.com/icons8/flat-color-icons",
	},
	{
		prefix: "fi",
		name: "Feather",
		description: "Simply beautiful icons",
		totalIcons: 287,
		license: "MIT",
		url: "https://feathericons.com/",
	},
	{
		prefix: "gi",
		name: "Game Icons",
		description: "Icons for games",
		totalIcons: 4040,
		license: "CC BY 3.0",
		url: "https://game-icons.net/",
	},
	{
		prefix: "go",
		name: "Github Octicons",
		description: "GitHub's icons",
		totalIcons: 264,
		license: "MIT",
		url: "https://octicons.github.com/",
	},
	{
		prefix: "gr",
		name: "Grommet-Icons",
		description: "Grommet UI icons",
		totalIcons: 635,
		license: "Apache License v2.0",
		url: "https://github.com/grommet/grommet-icons",
	},
	{
		prefix: "hi",
		name: "Heroicons",
		description: "Tailwind UI icons",
		totalIcons: 460,
		license: "MIT",
		url: "https://github.com/tailwindlabs/heroicons",
	},
	{
		prefix: "hi2",
		name: "Heroicons 2",
		description: "Heroicons v2",
		totalIcons: 888,
		license: "MIT",
		url: "https://github.com/tailwindlabs/heroicons",
	},
	{
		prefix: "im",
		name: "IcoMoon Free",
		description: "IcoMoon icon set",
		totalIcons: 491,
		license: "CC BY 4.0",
		url: "https://github.com/Keyamoon/IcoMoon-Free",
	},
	{
		prefix: "io",
		name: "Ionicons 4",
		description: "Ionic Framework icons v4",
		totalIcons: 696,
		license: "MIT",
		url: "https://ionicons.com/",
	},
	{
		prefix: "io5",
		name: "Ionicons 5",
		description: "Ionic Framework icons v5",
		totalIcons: 1332,
		license: "MIT",
		url: "https://ionicons.com/",
	},
	{
		prefix: "lia",
		name: "Icons8 Line Awesome",
		description: "Beautiful icon set",
		totalIcons: 1544,
		license: "MIT",
		url: "https://icons8.com/line-awesome",
	},
	{
		prefix: "lu",
		name: "Lucide",
		description: "Fork of Feather Icons",
		totalIcons: 1215,
		license: "ISC",
		url: "https://lucide.dev/",
	},
	{
		prefix: "md",
		name: "Material Design Icons",
		description: "Google's Material Design icons",
		totalIcons: 4341,
		license: "Apache License v2.0",
		url: "http://google.github.io/material-design-icons/",
	},
	{
		prefix: "pi",
		name: "Phosphor Icons",
		description: "Flexible icon family",
		totalIcons: 9072,
		license: "MIT",
		url: "https://github.com/phosphor-icons/core",
	},
	{
		prefix: "ri",
		name: "Remix Icon",
		description: "Neutral-style icon system",
		totalIcons: 2860,
		license: "Apache License v2.0",
		url: "https://github.com/Remix-Design/RemixIcon",
	},
	{
		prefix: "rx",
		name: "Radix Icons",
		description: "Radix UI Icon set",
		totalIcons: 318,
		license: "MIT",
		url: "https://icons.radix-ui.com",
	},
	{
		prefix: "si",
		name: "Simple Icons",
		description: "Brand icons",
		totalIcons: 3209,
		license: "CC0 1.0 Universal",
		url: "https://simpleicons.org/",
	},
	{
		prefix: "sl",
		name: "Simple Line Icons",
		description: "Simple and clean line icons",
		totalIcons: 189,
		license: "MIT",
		url: "https://thesabbir.github.io/simple-line-icons/",
	},
	{
		prefix: "tb",
		name: "Tabler Icons",
		description: "Fully customizable icons",
		totalIcons: 5237,
		license: "MIT",
		url: "https://github.com/tabler/tabler-icons",
	},
	{
		prefix: "tfi",
		name: "Themify Icons",
		description: "Themify icon set",
		totalIcons: 352,
		license: "MIT",
		url: "https://github.com/lykmapipo/themify-icons",
	},
	{
		prefix: "ti",
		name: "Typicons",
		description: "Rounded icon set",
		totalIcons: 336,
		license: "CC BY-SA 3.0",
		url: "http://s-ings.com/typicons/",
	},
	{
		prefix: "vsc",
		name: "VS Code Icons",
		description: "Visual Studio Code icons",
		totalIcons: 461,
		license: "CC BY 4.0",
		url: "https://github.com/microsoft/vscode-codicons",
	},
	{
		prefix: "wi",
		name: "Weather Icons",
		description: "Weather-themed icons",
		totalIcons: 219,
		license: "SIL OFL 1.1",
		url: "https://erikflowers.github.io/weather-icons/",
	},
];
